-- MySQL Script generated by MySQL Workbench
-- Mon Jan  8 11:10:15 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Book`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Book` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Book` (
  `BookID` INT NOT NULL,
  `Title` TEXT NULL,
  `TitleVI` TEXT NULL,
  `NumPages` INT NULL,
  `PublicationDate` DATE NULL,
  `ISBN13` VARCHAR(45) NULL,
  `AvgRating` FLOAT NULL,
  `CountRating` INT NULL,
  `Summary` TEXT NULL,
  `Genres` TEXT NULL,
  `Image` FLOAT NULL,
  `Language` VARCHAR(45) NULL,
  `Dimension` VARCHAR(45) NULL,
  `UnitPrice` FLOAT NULL,
  `Quantity` INT NULL,
  PRIMARY KEY (`BookID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Customer` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Customer` (
  `CustomerID` VARCHAR(20) NOT NULL,
  `CustomerIP` VARCHAR(45) NULL,
  `username` VARCHAR(45) NULL,
  `token` VARCHAR(45) NULL,
  PRIMARY KEY (`CustomerID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CustomerProfile`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`CustomerProfile` ;

CREATE TABLE IF NOT EXISTS `mydb`.`CustomerProfile` (
  `Age` INT NULL,
  `Gender` VARCHAR(45) NULL,
  `Email` VARCHAR(45) NULL,
  `Phone` VARCHAR(12) NULL,
  `CustomerName` VARCHAR(50) NULL,
  `CustomerID` VARCHAR(20) NOT NULL,
  INDEX `fk_CustomerProfile_Customer_idx` (`CustomerID` ASC) VISIBLE,
  PRIMARY KEY (`CustomerID`),
  CONSTRAINT `fk_CustomerProfile_Customer`
    FOREIGN KEY (`CustomerID`)
    REFERENCES `mydb`.`Customer` (`CustomerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Address` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Address` (
  `AddressID` INT NOT NULL,
  `Status` VARCHAR(10) NULL,
  `City` VARCHAR(45) NULL,
  `Street` VARCHAR(45) NULL,
  `District` VARCHAR(45) NULL,
  `Ward` VARCHAR(45) NULL,
  `CustomerID` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`AddressID`, `CustomerID`),
  INDEX `fk_Address_Customer1_idx` (`CustomerID` ASC) VISIBLE,
  CONSTRAINT `fk_Address_Customer1`
    FOREIGN KEY (`CustomerID`)
    REFERENCES `mydb`.`Customer` (`CustomerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Session`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Session` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Session` (
  `SessionID` VARCHAR(100) NOT NULL,
  `StartTime` DATETIME NULL,
  `EndTime` DATETIME NULL,
  `CustomerID` VARCHAR(20) NULL,
  PRIMARY KEY (`SessionID`),
  INDEX `fk_Session_Customer1_idx` (`CustomerID` ASC) VISIBLE,
  CONSTRAINT `fk_Session_Customer1`
    FOREIGN KEY (`CustomerID`)
    REFERENCES `mydb`.`Customer` (`CustomerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ShoppingCart`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ShoppingCart` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ShoppingCart` (
  `ShoppingCartID` VARCHAR(45) NOT NULL,
  `TotalProduct` INT NULL,
  `TotalCost` FLOAT NULL,
  `SessionID` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`ShoppingCartID`),
  INDEX `fk_ShoppingCart_Session1_idx` (`SessionID` ASC) VISIBLE,
  CONSTRAINT `fk_ShoppingCart_Session1`
    FOREIGN KEY (`SessionID`)
    REFERENCES `mydb`.`Session` (`SessionID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ShoppingCartDetail`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ShoppingCartDetail` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ShoppingCartDetail` (
  `Quantity` INT NULL,
  `ShoppingCartID` VARCHAR(45) NOT NULL,
  `BookID` INT NOT NULL,
  `DateAdded` DATETIME NULL,
  INDEX `fk_ShoppingCartDetail_ShoppingCart1_idx` (`ShoppingCartID` ASC) VISIBLE,
  PRIMARY KEY (`BookID`, `ShoppingCartID`),
  CONSTRAINT `fk_ShoppingCartDetail_ShoppingCart1`
    FOREIGN KEY (`ShoppingCartID`)
    REFERENCES `mydb`.`ShoppingCart` (`ShoppingCartID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ShoppingCartDetail_Book1`
    FOREIGN KEY (`BookID`)
    REFERENCES `mydb`.`Book` (`BookID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`WebActivity`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`WebActivity` ;

CREATE TABLE IF NOT EXISTS `mydb`.`WebActivity` (
  `ActivityID` INT NOT NULL,
  `ActivityType` VARCHAR(45) NULL,
  `ActivityDuration` INT NULL,
  `CreatedAt` DATETIME NULL,
  `UpdatedAt` DATETIME NULL,
  `SessionID` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`ActivityID`),
  INDEX `fk_WebActivity_Session1_idx` (`SessionID` ASC) VISIBLE,
  CONSTRAINT `fk_WebActivity_Session1`
    FOREIGN KEY (`SessionID`)
    REFERENCES `mydb`.`Session` (`SessionID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`BookActivity`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`BookActivity` ;

CREATE TABLE IF NOT EXISTS `mydb`.`BookActivity` (
  `InteractionNums` INT NULL,
  `WebActivity_ActivityID` INT NOT NULL,
  `BookID` INT NOT NULL,
  PRIMARY KEY (`WebActivity_ActivityID`, `BookID`),
  INDEX `fk_BookActivity_Book1_idx` (`BookID` ASC) VISIBLE,
  CONSTRAINT `fk_BookActivity_WebActivity1`
    FOREIGN KEY (`WebActivity_ActivityID`)
    REFERENCES `mydb`.`WebActivity` (`ActivityID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_BookActivity_Book1`
    FOREIGN KEY (`BookID`)
    REFERENCES `mydb`.`Book` (`BookID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Order` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Order` (
  `OrderID` VARCHAR(45) NOT NULL,
  `TotalProduct` INT NULL,
  `TotalCost` FLOAT NULL,
  `CreatedDate` DATETIME NULL,
  `FinishedDate` DATETIME NULL,
  `OrderStatus` VARCHAR(45) NULL,
  `CustomerID` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`OrderID`),
  INDEX `fk_Order_Customer1_idx` (`CustomerID` ASC) VISIBLE,
  CONSTRAINT `fk_Order_Customer1`
    FOREIGN KEY (`CustomerID`)
    REFERENCES `mydb`.`Customer` (`CustomerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Transaction`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Transaction` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Transaction` (
  `TransactionID` INT NOT NULL,
  `CreateAt` DATETIME NULL,
  `TotalPrice` FLOAT NULL,
  `TransactionStatus` VARCHAR(45) NULL,
  `CustomerID` VARCHAR(20) NOT NULL,
  `OrderID` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`TransactionID`),
  INDEX `fk_Transaction_Customer1_idx` (`CustomerID` ASC) VISIBLE,
  INDEX `fk_Transaction_Order1_idx` (`OrderID` ASC) VISIBLE,
  CONSTRAINT `fk_Transaction_Customer1`
    FOREIGN KEY (`CustomerID`)
    REFERENCES `mydb`.`Customer` (`CustomerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Transaction_Order1`
    FOREIGN KEY (`OrderID`)
    REFERENCES `mydb`.`Order` (`OrderID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`OrderDetails`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`OrderDetails` ;

CREATE TABLE IF NOT EXISTS `mydb`.`OrderDetails` (
  `Quantity` INT NULL,
  `TotalCost` FLOAT NULL,
  `OrderID` VARCHAR(45) NOT NULL,
  `BookID` INT NOT NULL,
  `Rating` INT NULL,
  PRIMARY KEY (`OrderID`, `BookID`),
  INDEX `fk_OrderDetails_Order1_idx` (`OrderID` ASC) VISIBLE,
  INDEX `fk_OrderDetails_Book1_idx` (`BookID` ASC) VISIBLE,
  CONSTRAINT `fk_OrderDetails_Order1`
    FOREIGN KEY (`OrderID`)
    REFERENCES `mydb`.`Order` (`OrderID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_OrderDetails_Book1`
    FOREIGN KEY (`BookID`)
    REFERENCES `mydb`.`Book` (`BookID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Author`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Author` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Author` (
  `AuthorID` INT NOT NULL,
  `AuthorName` VARCHAR(45) NULL,
  PRIMARY KEY (`AuthorID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`BookAuthor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`BookAuthor` ;

CREATE TABLE IF NOT EXISTS `mydb`.`BookAuthor` (
  `AuthorID` INT NOT NULL,
  `BookID` INT NOT NULL,
  PRIMARY KEY (`AuthorID`, `BookID`),
  INDEX `fk_Author_has_Book_Book1_idx` (`BookID` ASC) VISIBLE,
  INDEX `fk_Author_has_Book_Author1_idx` (`AuthorID` ASC) VISIBLE,
  CONSTRAINT `fk_Author_has_Book_Author1`
    FOREIGN KEY (`AuthorID`)
    REFERENCES `mydb`.`Author` (`AuthorID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Author_has_Book_Book1`
    FOREIGN KEY (`BookID`)
    REFERENCES `mydb`.`Book` (`BookID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`BookDescription`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`BookDescription` ;

CREATE TABLE IF NOT EXISTS `mydb`.`BookDescription` (
  `Description` TEXT NULL,
  `BookID` INT NOT NULL,
  PRIMARY KEY (`BookID`),
  INDEX `fk_BookDescription_Book1_idx` (`BookID` ASC) VISIBLE,
  CONSTRAINT `fk_BookDescription_Book1`
    FOREIGN KEY (`BookID`)
    REFERENCES `mydb`.`Book` (`BookID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`BookImage`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`BookImage` ;

CREATE TABLE IF NOT EXISTS `mydb`.`BookImage` (
  `ImgURL` TINYTEXT NULL,
  `ImgID` INT NOT NULL,
  `BookID` INT NOT NULL,
  PRIMARY KEY (`ImgID`, `BookID`),
  INDEX `fk_BookImage_Book1_idx` (`BookID` ASC) VISIBLE,
  CONSTRAINT `fk_BookImage_Book1`
    FOREIGN KEY (`BookID`)
    REFERENCES `mydb`.`Book` (`BookID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`BookType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`BookType` ;

CREATE TABLE IF NOT EXISTS `mydb`.`BookType` (
  `BookTypeID` VARCHAR(20) NOT NULL,
  `BookTypeName` VARCHAR(45) NULL,
  PRIMARY KEY (`BookTypeID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Book_has_BookType`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Book_has_BookType` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Book_has_BookType` (
  `BookID` INT NOT NULL,
  `BookTypeID` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`BookID`, `BookTypeID`),
  INDEX `fk_Book_has_BookType_BookType1_idx` (`BookTypeID` ASC) VISIBLE,
  INDEX `fk_Book_has_BookType_Book1_idx` (`BookID` ASC) VISIBLE,
  CONSTRAINT `fk_Book_has_BookType_Book1`
    FOREIGN KEY (`BookID`)
    REFERENCES `mydb`.`Book` (`BookID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Book_has_BookType_BookType1`
    FOREIGN KEY (`BookTypeID`)
    REFERENCES `mydb`.`BookType` (`BookTypeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
